### ISSUE TITLE
Support multi-Swift-version testing

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Package-Builder#96] opened 2017-03-20 21:46 UTC
As we update code to support new Swift versions and maintain backwards compatibility with older Swift versions, we should be testing repos on multiple Swift toolchain versions.

In addition, it has came to light that [many of our repos do not pass on 3.0.2](https://github.com/IBM-Swift/Kitura/issues/1039). Adding multi-version testing to CI tests can help catch this and alert repo owners to update their code.

**Comment by rolivieri** [comment] 2017-03-21 19:23
@youming-lin This issue seems to be a duplicate of https://github.com/IBM-Swift/DevOps/issues/119.

**Comment by rolivieri** [comment] 2017-03-21 19:49
@youming-lin If this issue matches the issue we already had for implementing additional test cases (https://github.com/IBM-Swift/DevOps/issues/119), we can close this one. Otherwise, let's discuss to understand what the difference is.

**Comment by youming-lin** [comment] 2017-03-21 19:53
I'm not sure what is the scope of that issue. This issue is about running the same unit tests we've been running, but across multiple Swift versions. There is some discussion/desire to keep Kitura et al. compatible with the latest Swift version as well as previous versions, and being able to test the code across multiple Swift versions would be the next step.

**Comment by rolivieri** [comment] 2017-03-21 20:06
@youming-lin One of the points that issue (IBM-Swift/DevOps#119) should address is ensuring that the logic in Package-Builder for obtaining different versions of Swift does indeed work. We currently have a few test cases for this but we will probably need more. I believe this is what you are asking for here. If so, we had already issue IBM-Swift/DevOps#119 in place. As for validating that Kitura (or any other repo) compiles with a given version of Swift, that's up to the repo owner...

**Comment by youming-lin** [comment] 2017-03-21 20:32
Bringing in @carlbrown and @kweinmeister for their thoughts.

Given that 3.1 does indeed bring some breaking changes over 3.0.2 on Linux, I think it's a good idea if we can test all future Kitura changes on both 3.1 and 3.0.2 and ensure that any new code that works on 3.1 will work on 3.0.2, and vice versa. And the more we can automate this, the better.

**Comment by rolivieri** [comment] 2017-03-21 20:43
@youming-lin So I just caught up with @kweinmeister... my thinking is that this is not an issue for Package-Builder. Now, you could implement a script that acts as a driver and uses Package-Builder to validate any number of repos. However, I don't think it is the responsibility of Package-Builder to have logic and be aware of all the repos that are in our organization... and much less have the responsibility to scan them on a regular basis. That, instead, could be the responsibility of an external script.

**Comment by carlbrown** [comment] 2017-03-21 20:45
I agree. And once 3.1 is official, then we should build everything against "release" 3.1 and against the latest `master` snapshot.  That way, if we suddenly start failing against `master`, then we know that we have an issue to investigate (and potentially open a bug with Apple).

**Comment by youming-lin** [comment] 2017-03-21 20:50
If we want to support backwards compatibility, I think it's important to integrate different Swift versions into CI tests. And this is distinct from scanning all repos; as new changes are merged into a given repo, to ensure backwards compatibility we should be running CI tests on all supported Swift versions. This would be an additional dimension of testing, somewhat analogous to running tests on multiple OSes.

**Comment by rolivieri** [comment] 2017-03-21 22:05
@carlbrown OK, sounds good. Feel free to reach out to discuss more when you are ready to make changes to the current script you have so that it can act as a driver and leverage Package-Builder.

**Comment by christiancompton** [comment] 2017-05-04 03:42
This was accomplished by https://github.com/IBM-Swift/DevOps/issues/141

**Closed as completed** 2017-05-04 03:41 UTC
Labels: devops
